### ISSUE TITLE
Zmiana domeny?

### ISSUE THREAD

**Issue by hbaniecki** [MI2DataLab/crs19-monitor#13]
https://covid-monitor.mi2.ai
https://covid-monitor.mi2datalab.com

**Comment by pbiecek** [comment]
Dwie domeny:
monitoring sytuacji w Polsce -> monitor.crs19.pl (jako że część osób juz zna ten link)
monitoring oparty o sytuacje w Europie -> monitor.mi2.ai
z crosslinkowaniem
do dyskusji na najbliższym spotkaniu

**Comment by pbiecek** [comment]
monitor.mi2.ai
