### ISSUE TITLE
Kompresja wykresów

### ISSUE THREAD

**Issue by piotrpiatyszek** [MI2DataLab/crs19-monitor#34]
W obecnej postaci dane z jednego dnia zajmują 275MB. Poniżej wrzucam listę ile zajmują sumarycznie pliki o danej nazwie. Napewno możemy dodać pliki .rda do gitignore i trzymać je tylko na naszym serwerze. 
```
125M     gg_objects.rda
53M      liczba_warianty_5.svg
30M      liczba_warianty_2.svg
24M      liczba_loc_1.svg
14M      liczba_loc_2.svg
6.6M     liczba_warianty_3.svg
5.3M     liczba_warianty_1.svg
3.5M     mapa_mutacje.svg
3.3M     liczba_warianty_4.svg
3.3M     udzial_warianty_4.svg
2.1M     udzial_warianty_1.svg
2.1M     liczba_seq_2.svg
1.6M     udzial_warianty_3.svg
1.5M     udzial_warianty_2.svg
1.3M     liczba_seq_1.svg
528K     index.html
264K     i18n.json
132K     placeholders.json
4.0K     regions.json
```

**Comment by pbiecek** [comment]
liczba_warianty_5.svg is reduced in
https://github.com/MI2DataLab/crs19-monitor/commit/e7803dd07e7d948fb2f99a86092c08ea13283b5d
https://github.com/MI2DataLab/crs19-monitor/commit/8920fe56dabe1854a26f622ccccb5f835447e997

**Comment by pbiecek** [comment]
liczba_loc_1.svg and liczba_loc_2.svg are reduced in 

https://github.com/MI2DataLab/crs19-monitor/commit/d48d26df18c875665a106a9ff714b00944249e6b
https://github.com/MI2DataLab/crs19-monitor/commit/188c8d0643c36ec0ca2bea3f5ee227d482ede916
https://github.com/MI2DataLab/crs19-monitor/commit/48db87932390e8c3bb79af16a008fea9a440b25e

**Comment by pbiecek** [comment]
gg_objects are not versioned dur to https://github.com/MI2DataLab/crs19-monitor/commit/be281e59d16be1bb8d7b9cfeb2f492f3dffb9c5f

**Comment by pbiecek** [comment]
liczba_warianty_2.svg are reduced with https://github.com/MI2DataLab/crs19-monitor/commit/e0ade802311fd08cb7d6e142a433a2e3a9aef0a0

**Comment by piotrpiatyszek** [comment]
New values are much better
```
14M    liczba_warianty_5.png
8.8M   liczba_loc_1.svg
8.3M   liczba_warianty_3.svg
7.1M   liczba_warianty_1.svg
7.0M   liczba_warianty_2.svg
6.1M   liczba_loc_2.svg
4.3M   liczba_warianty_4.svg
4.2M   udzial_warianty_4.svg
3.6M   mapa_mutacje.svg
2.7M   udzial_warianty_1.svg
2.1M   liczba_seq_2.svg
2.0M   udzial_warianty_2.svg
2.0M   udzial_warianty_3.svg
1.3M   liczba_seq_1.svg
528K   index.html
264K   i18n.json
132K   placeholders.json
4.0K   regions.json
```
Thanks
