### ISSUE TITLE
Monitor [...] in Poland -> in Europe

### ISSUE THREAD

**Issue by hbaniecki** [MI2DataLab/crs19-monitor#37]
Poprawić nagłówki na stronie

![image](https://user-images.githubusercontent.com/32574004/112769664-7f106200-9022-11eb-972a-ec5d75aa8c0e.png)

![image](https://user-images.githubusercontent.com/32574004/112769673-8e8fab00-9022-11eb-90bc-3b25a4887b95.png)

**Comment by pbiecek** [comment]
regions
