### ISSUE TITLE
Lista mutacji alertowych

### ISSUE THREAD

**Issue by pbiecek** [MI2DataLab/crs19-monitor#55]
Dla wariantu V3 (brazylijski)
3-7 poza N501Y i 484K

**Comment by pbiecek** [comment]
indyjski

**Comment by maciej-lukasik-va** [comment]
Południowo Afrykański B.1.351: K417N,E484K,N501Y
Indyjski B.1.617: E484Q, L452R, P681R
B.1.1.222: T478K

**Comment by hbaniecki** [comment]
https://covariants.org/shared-mutations

**Comment by hbaniecki** [comment]
https://www.ecdc.europa.eu/en/covid-19/variants-concern

**Comment by pbiecek** [comment]
now we are using WHO nomenclature
