### ISSUE TITLE
sposoby wizualizacji zagregowanej informacji o częstości mutacji alertowych

### ISSUE THREAD

**Issue by pbiecek** [MI2DataLab/crs19-monitor#56]
w krajach
np pheatmap

**Comment by pbiecek** [comment]
kraj na mutacja - procenty wystepowania
jezeli za duzo mutacji to ograniczyc sie tylko do spike

**Comment by maciej-lukasik-va** [comment]
![clustermap](https://user-images.githubusercontent.com/71699490/117371296-f231b180-aec7-11eb-8bca-83febcb64150.png)
![newplot (13)](https://user-images.githubusercontent.com/71699490/117371303-f5c53880-aec7-11eb-992d-a99dc2a49989.png)
![newplot (14)](https://user-images.githubusercontent.com/71699490/117371316-f8c02900-aec7-11eb-9e9b-1d3548701f7f.png)

**Comment by maciej-lukasik-va** [comment]
![clustermap_spike](https://user-images.githubusercontent.com/71699490/117371816-cf53cd00-aec8-11eb-80b1-f35e80c0ba03.png)
![spike](https://user-images.githubusercontent.com/71699490/117371829-d4188100-aec8-11eb-9f6e-c54cf5404ebf.png)

**Comment by pbiecek** [comment]
usunąć env

**Comment by pbiecek** [comment]
dla danych z ostatniego miesiaca

**Comment by pbiecek** [comment]
use case: pokazać tempo przyrostu udziału poszczególnych mutacji w spike
na początek można wykorzystać dane o Anglii

**Comment by pbiecek** [comment]
do prezentacji na środę
