### ISSUE TITLE
nazwy dla monitora

### ISSUE THREAD

**Issue by pbiecek** [MI2DataLab/crs19-monitor#60]

**Comment by HaZdula** [comment]
Mi2AgainstCovid
MonitorMi2AI
CRS19
CovidMi2
Covar

**Comment by HaZdula** [comment]
Mi2_Against_Covid
Monitor_Mi2_AI
CRS19
Covid_Mi2
Covar

**Comment by pbiecek** [comment]
MI2againstCOVID

**Comment by pbiecek** [comment]
https://twitter.com/mi2monitor
