### ISSUE TITLE
Broader documentation

### ISSUE THREAD

**Issue by michalkowalski94** [MI2DataLab/crs19-monitor#83]
Hello developers / collaborators
While trying to use Your scrapper and pipeline, i came acrtoss couple of problems regarding couple of steps:
1. In task_fasta_to_clades there is no information about which GFF file should be used and the NCBI one does not fit (headers are different).
2.  In task_fasta_to_pango scorpio for some reason do not want to work. I'm asking myself, since this step is performed with snakemake, wouldn't be more easier to use whole different environment dedicated to pangolin?
3. In task fasta to mutations there is needed an XML, but cannot really find reference what should be in this file.

Thank You for creating this pipeline and i hope my questions won't be any problem for You.

Cheers

**Comment by piotrpiatyszek** [comment]
Hello,
I've made some updates to the documentation.
1. You can run
```
UPDATE_REFERENCE=1 python scripts/task_fasta_to_clades.py
```
to download reference files used by nextclade.
2. I do not know the problem with scorpio, but we do not have it even installed.
3. Fasta to mutation was never used in production. However, it needs only fasta files and `db.fa` which is in the repo.
That is our main pipeline https://imgur.com/a/setzt50
and more details you can find in airflow config https://github.com/MI2DataLab/crs19-monitor/blob/main/scripts/airflow_dag.example.py

**Comment by piotrpiatyszek** [comment]
Update to 2
Pangolin started using `scorpio` in the 3.0 version. We still use 2.4.2. Looking at the changelog, this update does not look stable.
